# Generated by Django 3.0.5 on 2020-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_arrdelstest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_repartition',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
