# Generated by Django 3.0.5 on 2020-10-22 18:13

from django.db import migrations, models
import djongo.models.fields
import projects_similarities_computer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrepartition', models.CharField(max_length=80)),
                ('others_projects', djongo.models.fields.ArrayField(model_container=projects_similarities_computer.models.SimilarityItem)),
            ],
        ),
    ]
